version: "2.1"

networks:
  welearn_network-ci:
    driver: "bridge"

services:
  mariadb-ci:
    container_name: mariadb-ci
    image: mariadb:10.4
    networks:
      - "welearn_network-ci"
    environment:
      - "MYSQL_USER=welearn"
      - "MYSQL_PASSWORD=welearn"
      - "MYSQL_ROOT_PASSWORD=welearn"
      - "MYSQL_DATABASE=welearn"
    ports:
      - "3307:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 15s
      timeout: 30s
      retries: 6

  welearn-ci:
    container_name: welearn-backend-ci
    image: test1996/welearn-backend:latest
    networks:
      - "welearn_network-ci"
    ports:
      - "8081:8080"
    restart: always
    entrypoint: java -Dspring.profiles.active=docker -jar welearn.jar
    depends_on:
      - mariadb-ci
    volumes:
      - ./data:/data
    healthcheck:
     test: "curl --fail --silent http://welearn-ci:8080/actuator/health | grep UP || exit 1"
     interval: 10s
     timeout: 30s
     retries: 10
    depends_on:
      mariadb-ci:
        condition: service_healthy

  welearn-front-end-ci:
    container_name: welearn-front-end-ci
    image: pesho02/welearn-front-end:latest
    ports:
      - "4200:80"
    networks:
      - "welearn_network-ci"